FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN mkdir -p scripts
COPY scripts/healthcheck.js ./scripts/healthcheck.js
RUN npm run build:server
COPY server/db/migrations/ /app/dist/db/migrations/
COPY server/db/seeds/ /app/dist/db/seeds/
EXPOSE 3000
CMD ["node", "/app/dist/server.js"]